### PR TITLE
First attempt at Kubernetes support

### PR DESCRIPTION
**Pull request by plwhite**
Kubernetes - deploys and containers start file, but not tested function.

### CODE REVIEW

**Comment by plwhite** [comment]
@MatMeredith Would you like to take this? Only issue is that I have not tested that connectivity between containers actually works correctly.

**Comment by leader-us** [comment]
There are some problems :

1 etcd container listens 2379 port  but others want access 2380
2 if docker images don't change cscf.sprout and scscf.sprout host to icscf_sprout and scscf_sprout ,then 
   releated kubernetes service can't connect network

  https://github.com/Metaswitch/clearwater-docker/issues/38

**Comment by plwhite** [comment]
This has been languishing somewhat - sorry. I do plan to move it forward again now.
- Agreed on the "." in the names of the services. With me to try and drive a resolution.
- I think the etcd container is listening on both ports 2379 and 2380, isn't it? I can telnet to both those ports at least.

**Comment by plwhite** [comment]
This is not suitable for merging - it involves changes to the base image that might conflict with requirements for Docker support. Hence closing PR (the branch however does seem to work, modulo intermittent failures of the deployment caused by issue #55).

**Pull request closed without merging**
