### PR TITLE
[Reviewer: Mat] Add Rogers to clearwater-docker

### PR DESCRIPTION
**Pull request by richardwhiuk**
Mat,

This updates Clearwater Docker to reflect that Astaire and Rogers are now two separate services.

### CODE REVIEW

**Comment by richardwhiuk** [comment]
Mat, we discussed this, and you were going to have a look at the Kubernetes changes and doing some testing of this

**Comment by MatMeredith** [comment]
@johadalin Adam: did you say that you were going to test the docker compose part?

**Comment by johadalin** [comment]
Sure thing

**Comment by johadalin** [comment]
@MatMeredith @richardwhiuk I think this is currently broken at least for the docker setup. I'm still seeing SIP 500 errors to the live tests, and i think we need to update https://github.com/Metaswitch/clearwater-infrastructure/blob/master/debian/clearwater-auto-config-docker.init.d#L96 as well. 
Fairly sure the issue is that things are contacting astaire when it should be rogers
Presumably this hits you on kubernetes too.

**Comment by johadalin** [comment]
OK. So, as discussed, we think the right end goal is to separate out Rogers, but atm we should co-locate it with astaire. I've done some testing with the latest code, both under docker compose and kubernetes, and can confirm that everything works as it now is. 
@richardwhiuk I've taken a look at the actual changes, and it all seems sensible. Passing back to you so we can get this in soon :+1:

**Pull request merged**
