### PR TITLE
Kubernetes

### PR DESCRIPTION
**Pull request by parwinderet**

### CODE REVIEW

**Comment by mirw** [comment]
@parwinderet, I suspect you're not actually looking to get this merged for now?  Assuming not, I'm assigning this pull request to you so that it doesn't accidentally get picked up and someone review it - please assign it to someone when you want it to be reviewed.  Thanks!

**Comment by resouer** [comment]
This is a very nice PR, why it is not get merged? 

The code/scripts of clearwater is buggy (full of hard coded DNS name). It should be fixed.

**Comment by mirw** [comment]
@parwinderet, are you looking to get this merged?  Please let us know.

@resouer, I think the current master branch works for stand-alone Docker (i.e. without Kubernetes) - I'm not sure whether the kubernetes branch works with stand-alone Docker - do you know?

Regarding "code/scripts of Clearwater is buggy (full of hard coded DNS name)", can you be more specific - are you referring to https://github.com/Metaswitch/clearwater-docker/blob/fab6292280fa9e324058e0bb818b50039038a013/base/Dockerfile#L47 or something else?

Thanks!

**Comment by resouer** [comment]
Yes, I am referring the DNS names in Dockerfiles. It concerns me a lot since [Kubernetes DNS ](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/)follows RFC while docker doesn't.

Btw, it seems `mgm_kubernetes` is a promising branch?

**Comment by parwinderet** [comment]
Hi,

Yes I am able to launch Clearwater and end to end call with kubernetes.
So want to merge my changes but not sure how to do that.

**Comment by resouer** [comment]
@parwinderet @mirw  Great to hear about it! Do you know anyone who has write access to this repo?

btw, I think you need to squash your commits before that.

**Comment by resouer** [comment]
@parwinderet I also noticed in your base's Dockefile, there is a `COPY repo_certs.zip /tmp/` which is outdated since no `repo_certs.zip` in this repo anymore. 

Maybe rebase && squash && re-test is needed.

**Comment by resouer** [comment]
Also cc @MatMeredith since you are working on `mgm_kubernetes` branch

**Pull request merged**
